// <auto-generated />
using System;
using WalletApp.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WalletApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WalletApp.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Coefficient")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ranks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("17ff6de9-52d0-4eae-94a1-00e18a51939b"),
                            Coefficient = 1.0,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1c35ff11-df37-4d9c-9077-7ebf6a0d52fb"),
                            Coefficient = 1.2,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6eaf3ae3-6b4c-4829-9307-b8552f85d340"),
                            Coefficient = 1.3999999999999999,
                            Status = 2
                        });
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("095cb701-0d66-48e0-91c3-1c6df110dcf2"),
                            LogoUrl = "http://localhost:3000/assets/icons/struzhka_icon.png",
                            Price = 200m,
                            Title = "Чоловіча стрижка"
                        },
                        new
                        {
                            Id = new Guid("c44a611e-52e9-46ef-8864-e1ca4df8aab7"),
                            LogoUrl = "http://localhost:3000/assets/icons/machine_icon.png",
                            Price = 150m,
                            Title = "Стрижка машинкою"
                        },
                        new
                        {
                            Id = new Guid("9040f34c-800c-4590-882a-37b8a608c676"),
                            LogoUrl = "http://localhost:3000/assets/icons/golinya_icon.png",
                            Price = 150m,
                            Title = "Гоління"
                        },
                        new
                        {
                            Id = new Guid("2bff2bab-0fa9-4731-9c5c-1058b8cb3675"),
                            LogoUrl = "http://localhost:3000/assets/icons/ukladka_icon.png",
                            Price = 100m,
                            Title = "Професійна укладка"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a"),
                            ConcurrencyStamp = "7acc740d-f2af-439b-bf57-fff95e4e5bba",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("7b47b6c2-dd7c-4054-93a3-13764fafb71a"),
                            ConcurrencyStamp = "041c970d-df9c-40b0-8783-ab8b5b84e199",
                            Name = "Barber",
                            NormalizedName = "BARBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 14,
                            ClaimType = "get:barber",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "create:barber",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "delete:barber",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "update:barber",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "get:client",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "create:client",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "delete:client",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "update:client",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "get:booking",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "create:booking",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "delete:booking",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "update:booking",
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "get:booking",
                            RoleId = new Guid("7b47b6c2-dd7c-4054-93a3-13764fafb71a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("672979c9-d851-4bb7-83b6-a75e906dbefa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "870e93e4-5b74-4249-901a-ba81d8ff8fd7",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKma5hRc/ULFSF5qpCmor7pN51bv0a1RA/UzIae2epsqZBHf1MxLoRHe17latE1CuQ==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4a272fa6-b098-4974-aaab-b89a6c68d8e0",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("672979c9-d851-4bb7-83b6-a75e906dbefa"),
                            RoleId = new Guid("313f353f-2ac2-4e56-9904-8826767b9c6a")
                        },
                        new
                        {
                            UserId = new Guid("ce4bb7c0-6614-4fdd-b782-5e854ed803e7"),
                            RoleId = new Guid("7b47b6c2-dd7c-4054-93a3-13764fafb71a")
                        },
                        new
                        {
                            UserId = new Guid("66f07b70-0485-4740-98fb-7b68c9137db6"),
                            RoleId = new Guid("7b47b6c2-dd7c-4054-93a3-13764fafb71a")
                        },
                        new
                        {
                            UserId = new Guid("3615f116-6534-4566-a6ef-eace03040563"),
                            RoleId = new Guid("7b47b6c2-dd7c-4054-93a3-13764fafb71a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Barber", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uuid");

                    b.HasIndex("RankId");

                    b.ToTable("Barbers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce4bb7c0-6614-4fdd-b782-5e854ed803e7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dbde3e0c-1bdc-4af2-9ef9-a2a181da5ba5",
                            Email = "maksym@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MAKSYM@GMAIL.COM",
                            NormalizedUserName = "MAKSYM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG9aT1yo8qaR+o9zYZMX2wwPQMMqpog2ZUG3sbXkBGd5++MRA9jh2XrGWDabsoZibw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "559d3995-d5a6-4964-85f7-8abad588b110",
                            TwoFactorEnabled = false,
                            UserName = "Максим",
                            Description = "Працюю барбером вже 3 роки",
                            PhotoUrl = "http://localhost:3000/assets/img/first_barber.jpg",
                            RankId = new Guid("17ff6de9-52d0-4eae-94a1-00e18a51939b")
                        },
                        new
                        {
                            Id = new Guid("66f07b70-0485-4740-98fb-7b68c9137db6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cd352105-2199-4274-9d25-cb48fc3b0aaf",
                            Email = "denys@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "DENYS@GMAIL.COM",
                            NormalizedUserName = "DENYS",
                            PasswordHash = "AQAAAAIAAYagAAAAEGK8DOxb3oOWVD7bhLOp6v/TS9fCWfRKwpVxh3jHcQAi+h4x1cFU8ScRq4euilYXrA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a36512cb-2d6e-44b3-bf26-f326ce97645e",
                            TwoFactorEnabled = false,
                            UserName = "Денис",
                            Description = "Зі мною можна поговорити",
                            PhotoUrl = "http://localhost:3000/assets/img/second_barber.jpg",
                            RankId = new Guid("1c35ff11-df37-4d9c-9077-7ebf6a0d52fb")
                        },
                        new
                        {
                            Id = new Guid("3615f116-6534-4566-a6ef-eace03040563"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54f49b3b-66c5-4265-a199-03c179443f6a",
                            Email = "artur@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ARTUR@GMAIL.COM",
                            NormalizedUserName = "Artur",
                            PasswordHash = "AQAAAAIAAYagAAAAEOepPUiFmfhIUdSWQHaNxglx7sayOPpbx8iR8UqO48wpM1uJZWC1iSZZK+JDrYpddw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "da6fadef-d7cb-4440-a6cd-2db167eaedad",
                            TwoFactorEnabled = false,
                            UserName = "Артур",
                            Description = "Доповню ваш образ гарною зачіскою",
                            PhotoUrl = "http://localhost:3000/assets/img/third_barber.jpg",
                            RankId = new Guid("6eaf3ae3-6b4c-4829-9307-b8552f85d340")
                        });
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("WalletApp.Domain.Entities.Barber", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletApp.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Barber", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("WalletApp.Domain.Entities.Barber", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletApp.Domain.Entities.Rank", "Rank")
                        .WithMany("Barbers")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("WalletApp.Domain.Entities.Rank", b =>
                {
                    b.Navigation("Barbers");
                });
#pragma warning restore 612, 618
        }
    }
}
